import{a as S,S as w,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();async function d(o,e){const a=new URLSearchParams({key:"51438211-e30b649eb0e533720cd6e7900",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e});try{let s=await S.get(`https://pixabay.com/api/?${a}`);if(s.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return s.data}catch(s){throw s}}const m=document.querySelector(".gallery"),q=new w(".gallery-link",{}),p=document.querySelector(".loader"),g=document.querySelector(".load-more-button");function y(o){let e=o.map(({webformatURL:a,largeImageURL:s,tags:t,likes:r,views:l,comments:v,downloads:E})=>`<li class="gallery-li">
        <a class="gallery-link" href="${s}">
            <img class="gallery-img" src="${a}" alt="${t}"/>
        </a>
        <div class="img-div">
            <p class="img-p">Likes<span class="img-span">${r}</span></p>
            <p class="img-p">Views<span class="img-span">${l}</span></p>
            <p class="img-p">Comments<span class="img-span">${v}</span></p>
            <p class="img-p">Downloads<span class="img-span">${E}</span></p>
            </div>
     </li>`).join("");m.insertAdjacentHTML("beforeend",e),q.refresh()}function $(){m.innerHTML=""}function h(){p.classList.remove("visually-hidden")}function u(){p.classList.add("visually-hidden")}function f(){g.classList.remove("visually-hidden")}function L(){g.classList.add("visually-hidden")}let i,c;const b=document.querySelector(".form"),H=document.querySelector(".load-more-button"),P=async o=>{if(o.preventDefault(),$(),L(),c=b.elements["search-text"].value.trim(),i=1,!c)n.error({title:"Error",message:"Input must not be empty"});else{h();try{let e=await d(c,i);u(),y(e.hits),i*15<e.totalHits?f():n.info({title:"Hello",message:"We're sorry, but you've reached the end of search results!"})}catch(e){u(),n.error({title:"Error",message:e.message})}}};b.addEventListener("submit",P);const B=async o=>{L(),h(),i+=1;try{let e=await d(c,i);u(),y(e.hits);const s=document.querySelector(".gallery-li").getBoundingClientRect().height;scrollBy({top:s*2+24,behavior:"smooth"}),i*15<e.totalHits?f():n.info({title:"Hello",message:"We're sorry, but you've reached the end of search results!"})}catch(e){u(),n.error({title:"Error",message:e.message})}};H.addEventListener("click",B);
//# sourceMappingURL=index.js.map
